---
version: "1.0"
services:
  dockerized-orcaslicer:
    image: simpleace/dockerized-orcaslicer
    container_name: dockerized-orcaslicer
    environment:
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=:0
      - VGL_DISPLAY=egl # needed to run without X server
      - SUPD_LOGLEVEL=INFO 
      - ENABLEHWGPU=true
      - VNC_RESOLUTION=1920x1080
    volumes:
      - ./prints:/prints/
      - ./data:/configs/
    restart: unless-stopped
