###

#Work in progress

###


ARG UBUNTU_VERSION=22.04

FROM nvidia/opengl:1.2-glvnd-runtime-ubuntu${UBUNTU_VERSION}

LABEL authors=" - SimpleAce"

ENV DEBIAN_FRONTEND noninteractive
ARG PUID=1000
ARG PGID=1000

# Install some basic dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget xorg xauth gosu supervisor x11-xserver-utils libegl1-mesa libgl1-mesa-glx \
    lxde gtk2-engines-murrine gnome-themes-standard gtk2-engines-pixbuf gtk2-engines-murrine arc-theme \
    freeglut3 libgtk2.0-dev libwxgtk3.0-gtk3-dev libwx-perl libxmu-dev libgl1-mesa-glx libgl1-mesa-dri  \
    xdg-utils locales locales-all pcmanfm jq curl git bzip2 gpg-agent software-properties-common \
    # Packages needed to support the AppImage changes. The libnvidia-egl-gbm1 package resolves an issue 
    # where GPU acceleration resulted in blank windows being generated.
    libwebkit2gtk-4.1-0 libnvidia-egl-gbm1 \
    && mkdir -p /usr/share/desktop-directories \
    # Install Firefox without Snap.
    && add-apt-repository ppa:mozillateam/ppa \
    && apt update \
    && apt install -y firefox-esr --no-install-recommends \
    # Clean everything up.
    && apt autoclean -y \
    && apt autoremove -y \
    && rm -rf /var/lib/apt/lists/*

# Install VirtualGL and noVNC
RUN curl -fsSL https://sourceforge.net/projects/virtualgl/files/2.6.2/VirtualGL_2.6.2_Linux_x86_64.tar.gz/download -o VirtualGL_2.6.2_Linux_x86_64.tar.gz \
    && tar xzf VirtualGL_2.6.2_Linux_x86_64.tar.gz \
    && cd virtualgl_2.6.2 \
    && ./virtualgl_run install \
    && cd .. \
    && apt-get update && apt-get install -y --no-install-recommends novnc websockify

# Install Prusaslicer.
WORKDIR /orcaslicer
ADD get_beta_orcaslicer_release.sh /orcaslicer

RUN mkdir -p /orcaslicer/orcaslicer-dist
RUN chmod -R 777 /orcaslicer/get_beta_orcaslicer_release.sh

# Retrieve and unzip all of the OrcaSlicer bits using variable.
RUN latestOrcaslicer=$(/orcaslicer/get_beta_orcaslicer_release.sh url) \
    && echo ${latestOrcaslicer} \
    && OrcaslicerReleaseName=$(/orcaslicer/get_beta_orcaslicer_release.sh name) \
    && curl -sSL ${latestOrcaslicer} > /orcaslicer/orcaslicer-dist/orcaslicer.AppImage \
    && chmod -R 775 /orcaslicer/orcaslicer-dist/orcaslicer.AppImage \
    && dd if=/dev/zero bs=1 count=3 seek=8 conv=notrunc of=orcaslicer-dist/orcaslicer.AppImage \
    && bash -c "/orcaslicer/orcaslicer-dist/orcaslicer.AppImage --appimage-extract"

RUN rm -rf /var/lib/apt/lists/*
RUN apt-get autoclean
RUN chmod -R 777 /orcaslicer/
RUN groupadd -g ${PGID} orcaslicer
RUN useradd -u ${PUID} -g orcaslicer --create-home --home-dir /home/orcaslicer orcaslicer
RUN mkdir -p /orcaslicer/
RUN mkdir -p /configs/
RUN mkdir -p /prints/
RUN chown -R orcaslicer:orcaslicer /orcaslicer/ /home/orcaslicer/ /prints/ /configs/
RUN locale-gen en_US
RUN mkdir /configs/.local
RUN mkdir -p /configs/.config/
RUN ln -s /configs/.config/ /home/orcaslicer/
RUN mkdir -p /home/orcaslicer/.config/
RUN mkdir -p /home/orcaslicer/.config/OrcaSlicer/

# We can now set the Download directory for Firefox and other browsers. 
# We can also add /prints/ to the file explorer bookmarks for easy access.
RUN echo "XDG_DOWNLOAD_DIR=\"/prints/\"" >> /home/orcaslicer/.config/user-dirs.dirs
RUN echo "file:///prints prints" >> /home/orcaslicer/.gtk-bookmarks

# Generate key for noVNC and cleanup errors.
    && rm /etc/xdg/autostart/lxpolkit.desktop \
    && mv /usr/bin/lxpolkit /usr/bin/lxpolkit.ORIG

ENV PATH ${PATH}:/opt/VirtualGL/bin:/opt/TurboVNC/bin

ADD entrypoint.sh /entrypoint.sh
ADD supervisord.conf /etc/

# Add a default file to resize and redirect, and adjust icons for noVNC.
ADD lxde-rc.xml /home/orcaslicer/.config/openbox/lxde-rc.xml 

# Set Firefox to run with hardware acceleration as if enabled.
RUN sed -i 's|exec $MOZ_LIBDIR/$MOZ_APP_NAME "$@"|if [ -n "$ENABLEHWGPU" ] \&\& [ "$ENABLEHWGPU" = "true" ]; then\n  exec /usr/bin/vglrun $MOZ_LIBDIR/$MOZ_APP_NAME "$@"\nelse\n  exec $MOZ_LIBDIR/$MOZ_APP_NAME "$@"\nfi|g' /usr/bin/firefox-esr

VOLUME /configs/
VOLUME /prints/

EXPOSE 3900

ENTRYPOINT ["/entrypoint.sh"]
