ARG UBUNTU_VERSION=22.04

FROM nvidia/opengl:1.2-glvnd-runtime-ubuntu${UBUNTU_VERSION}

LABEL authors=" - SimpleAce"

ARG VIRTUALGL_VERSION=3.1.1-20240228
ARG TURBOVNC_VERSION=3.1.1-20240127

ENV DEBIAN_FRONTEND=noninteractive
ENV DISPLAY=:0
ENV NO_VNC_PORT=8080
ENV RESOLUTION=1920x1080
ENV DPI=96

RUN apt-get update && apt-get install -y \
    curl ca-certificates gnupg git supervisor wget \
    libgtk-3-0 libglu1-mesa libxrender1 libxkbcommon-x11-0 \
    libxrandr2 libxtst6 libnss3 libatk1.0-0 libatk-bridge2.0-0 \
    libxcomposite1 libxdamage1 libxfixes3 libxext6 libx11-xcb1 \
    python3 xz-utils \
    && rm -rf /var/lib/apt/lists/*

# Install TurboVNC
RUN wget -qO- https://sourceforge.net/projects/turbovnc/files/${TURBOVNC_VERSION}/turbovnc_${TURBOVNC_VERSION}_amd64.deb/download \
    | dpkg -i /dev/stdin

# Install VirtualGL
RUN wget -qO- https://sourceforge.net/projects/virtualgl/files/${VIRTUALGL_VERSION}/virtualgl_${VIRTUALGL_VERSION}_amd64.deb/download \
    | dpkg -i /dev/stdin

# Install noVNC
RUN git clone https://github.com/novnc/noVNC.git /usr/share/novnc && \
    git clone https://github.com/novnc/websockify /usr/share/novnc/utils/websockify

# Download OrcaSlicer AppImage
RUN mkdir -p /opt/orcaslicer && \
    wget -O /opt/orcaslicer/OrcaSlicer.AppImage \
    https://github.com/SoftFever/OrcaSlicer/releases/download/nightly-builds/OrcaSlicer_Linux_AppImage_Ubuntu2404_V2.3.1-dev.AppImage && \
    chmod +x /opt/orcaslicer/OrcaSlicer.AppImage

# Create user and config directories
RUN useradd -ms /bin/bash orcaslicer && \
    mkdir -p /configs/.config/OrcaSlicer && \
    chown -R orcaslicer:orcaslicer /configs

# Add supervisord config
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

USER orcaslicer
WORKDIR /home/orcaslicer

EXPOSE 8080

CMD ["/usr/bin/supervisord"]
